# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28cf432c009ed990c44e90a2983a14b1bc4aae30bc83b92f198db80842d1940c5d04116cf0b7f8a80432e04aae90691406a2808acc5aceb6cc16734bfc9ec47f

test:
  secret_key_base: 8b482e9a72174a8fb5fc25d299c806da656bbc84b41f1b1f4b51022bc3319909872654a3e886716b2c7d26ab73dbb1f8965ae61585d046eac76850bf709f4565

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
